X( L"readers",               readers,               L"\r\n\t-- Lists available readers." )
X( L"connect",               connect,               L"<id>\r\n\t-- Connects to the card in the specied reader <id>." )
X( L"disconnect",            disconnect,            L"\r\n\t-- Disconnects from the card and reader." )
X( L"reset",                 reset,                 L"[cold / warm]\r\n\t-- Sends cold / warm reset to the card, and returns ATR." )
X( L"dump",                  dump,                  L"{hex string}\r\n\t-- Dumps hex string or last output to hex table." )
X( L"parse",                 parse,                 L"[atr {hex string} / {hex string}]\r\n\t-- Parses ATR / TLV hex string / TLV last rAPDU." )
X( L"raw",                   raw,                   L"{command}\r\n\t-- Transmits raw buffer to the card." )
X( L"apdu",                  apdu,                  L"CLA INS P1 P2 [Lc {buffer}] [Le]\r\n\t-- Transmits APDU command to the card." )
X( L"select",                select,                L"<first/next> <ascii/hex> <name>\r\n\t-- Sends select command to the card." )
